name: Options Bot Scheduler

on:
  schedule:
    # 9 PM IST → 15:30 UTC → generate suggestions
    - cron: '30 15 * * *'
    # 10 PM IST → 16:30 UTC → performance check (after market, when data might be available)
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install nsepython pandas numpy yfinance requests

      - name: Create empty CSV files if they don't exist
        run: |
          touch active_suggestions.csv
          touch all_history.csv

      - name: Determine MODE based on cron time
        id: setmode
        run: |
          CURRENT_HOUR_UTC=$(date -u +'%H')
          if [ "$CURRENT_HOUR_UTC" -eq 15 ]; then
            echo "mode=suggestions" >> $GITHUB_OUTPUT
          elif [ "$CURRENT_HOUR_UTC" -eq 16 ]; then
            echo "mode=performance" >> $GITHUB_OUTPUT
          else
            echo "mode=manual" >> $GITHUB_OUTPUT
          fi

      - name: Run app.py
        run: python app.py
        env:
          MODE: ${{ steps.setmode.outputs.mode }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit and push CSVs
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add active_suggestions.csv all_history.csv
          if git diff --staged --quiet; then
            echo "No changes to CSV files, skipping commit"
          else
            git commit -m "Update CSVs from workflow [$(date +'%Y-%m-%d %H:%M')]"
            git push origin main
          fi
