name: Options Bot Scheduler

on:
  schedule:
    # 9 PM IST → 15:30 UTC → generate suggestions
    - cron: '30 15 * * *'
    # 6 PM IST → 12:30 UTC → performance check
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install nsepython pandas numpy yfinance requests

      - name: Determine MODE based on cron time
        id: setmode
        run: |
          CURRENT_HOUR_UTC=$(date -u +'%H')
          if [ "$CURRENT_HOUR_UTC" -eq 15 ]; then
            echo "mode=suggestions" >> $GITHUB_OUTPUT
          elif [ "$CURRENT_HOUR_UTC" -eq 12 ]; then
            echo "mode=performance" >> $GITHUB_OUTPUT
          else
            echo "mode=manual" >> $GITHUB_OUTPUT

      - name: Run app.py
        run: python app.py
        env:
          MODE: ${{ steps.setmode.outputs.mode }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit and push CSVs
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add active_suggestions.csv all_history.csv || echo "No files to add"
          git commit -m "Update CSVs from workflow" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
